package com.nttdata.scs.selenium;

import java.util.HashMap;
import java.util.Map;

import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
// Generated by Selenium IDE
import org.openqa.selenium.By;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Keys;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.interactions.Actions;


public class CreateOpportunityRecordedTest {
	private WebDriver driver;
	private Map<String, Object> vars;
	JavascriptExecutor js;

	@BeforeEach
	public void setUp() {
		driver = new ChromeDriver();
		js = (JavascriptExecutor) driver;
		vars = new HashMap<String, Object>();
	}

	@AfterEach
	public void tearDown() {
		driver.quit();
	}

	@Test
	public void createOpportunityRecorded() {
		driver.get("https://trailhead-iaam-dev-ed.my.salesforce.com/");
		driver.manage().window().setSize(new Dimension(1680, 960));
//		{
//			WebElement element = driver.findElement(By.id("username"));
//			Actions builder = new Actions(driver);
//			builder.moveToElement(element).clickAndHold().perform();
//		}
//		{
//			WebElement element = driver.findElement(By.id("username"));
//			Actions builder = new Actions(driver);
//			builder.moveToElement(element).perform();
//		}
//		{
//			WebElement element = driver.findElement(By.id("username"));
//			Actions builder = new Actions(driver);
//			builder.moveToElement(element).release().perform();
//		}
//		driver.findElement(By.id("username")).click();
//		driver.findElement(By.id("username")).click();
//		{
//			WebElement element = driver.findElement(By.id("username"));
//			Actions builder = new Actions(driver);
//			builder.moveToElement(element).clickAndHold().perform();
//		}
//		{
//			WebElement element = driver.findElement(By.id("username"));
//			Actions builder = new Actions(driver);
//			builder.moveToElement(element).perform();
//		}
//		{
//			WebElement element = driver.findElement(By.id("username"));
//			Actions builder = new Actions(driver);
//			builder.moveToElement(element).release().perform();
//		}
		driver.findElement(By.id("username")).click();
		driver.findElement(By.id("username")).sendKeys("lazy.beaver@nttdata.com.iaam");
		driver.findElement(By.id("content")).click();
		driver.findElement(By.id("password")).sendKeys("REPLACE_THIS");
		driver.findElement(By.id("password")).sendKeys(Keys.ENTER);
		driver.findElement(By.cssSelector(".navItem:nth-child(6) use")).click();
		driver.findElement(By.cssSelector(".slds-dropdown__item:nth-child(5) .slds-truncate > span")).click();
		driver.findElement(By.linkText("Burlington Textiles Corp of America")).click();
		driver.findElement(By.linkText("Show more actions")).click();
		driver.findElement(By.linkText("New Opportunity")).click();
		{
			WebElement element = driver.findElement(By.linkText("New Opportunity"));
			Actions builder = new Actions(driver);
			builder.moveToElement(element).perform();
		}
		{
			WebElement element = driver.findElement(By.tagName("body"));
			Actions builder = new Actions(driver);
			builder.moveToElement(element, 0, 0).perform();
		}
		driver.findElement(By.id("3867:0")).sendKeys("Selenium Test Opportunity");
		driver.findElement(By.linkText("--None--")).click();
		driver.findElement(By.linkText("Value Proposition")).click();
		driver.findElement(By.id("4071:0")).click();
		driver.findElement(By.id("4140:0")).click();
		driver.findElement(By.id("4140:0")).sendKeys("We will see");
		driver.findElement(By.cssSelector(".slds-button_brand > .label")).click();
		{
			WebElement element = driver.findElement(By.cssSelector(".slds-button_brand > .label"));
			Actions builder = new Actions(driver);
			builder.moveToElement(element).perform();
		}
	}
}
